const restaurants = [
  {
    id: "r1",
    name: "Spice villa cafe & restro Newai",
    cuisine: "Fast Food",
    rating: 4.4,
    time: "30 mins",
    minOrder: 99,
    image: "assets/images/spice-villa2.jpg",
    menu: [
      { id: "m1", name: "VEG. BURGER", price: 70, veg: true, image: "assets/images/Veg-Burger.jpg"},
      { id: "m2", name: "PANEER BURGER", price: 90, veg: true, image: "assets/images/paneer-burger.jfif"},
      { id: "m3", name: "VEG. GRILL SANDWICH", price: 80, veg: true, image: "assets/images/veg-grill-sandwich.jfif" },
      { id: "m4", name: "PANEER GRILL SANDWICH", price: 100, veg: true, image: "assets/images/Paneer-Sandwich.jpg" },
      { id: "m5", name: "PERI PERI FRIES", price: 120, veg: true, image: "assets/images/peri-peri-fries.jfif" },
      { id: "m6", name: "PLAIN MAGGIE", price: 60, veg: true, image: "assets/images/plain-maggi.jpeg" },
      { id: "m7", name: "PANEER MAGGIE", price: 80, veg: true, image: "assets/images/paneer-maggi.jpg" },
      { id: "m8", name: "VEG. CHOWMIN", price: 90, veg: true, image: "assets/images/veg-chowmin.jfif" },
      { id: "m9", name: "RED SAUSE PASTA", price: 130, veg: true, image: "assets/images/red-sauce-pasta.webp" },
      { id: "m10", name: "WHITE SAUSE PASTA", price: 160, veg: true, image: "assets/images/White-Sauce-Paste.jpg" },
      { id: "m11", name: "BHEL PURI", price: 60, veg: true, image: "assets/images/bhel-puri.jpg" },
      { id: "m12", name: "PANEER ROLL", price: 130, veg: true, image: "assets/images/PaneerRoll.jpg" },
      { id: "m13", name: "VEG. FRIED MOMO(8PCS)", price: 90, veg: true, image: "assets/images/fried-momo.webp" },
      { id: "m14", name: "VEG. STEAM MOMO(8PCS)", price: 110, veg: true, image: "assets/images/steam-momo.jpg" },
      { id: "m15", name: "MARGHERITA PIZZA", price: 150, veg: true, image: "assets/images/Pizza_Margherita.jpg" },
      { id: "m16", name: "PANEER PIZZA", price: 190, veg: true, image: "assets/images/Paneer-Pizza.jpg" },
      { id: "m17", name: "VEG OTC PIZZA", price: 170, veg: true, image: "assets/images/veg-pizza.webp" },
    ]
  },
  {
    id: "r2",
    name: "Swaad Cafe and Restaurant",
    cuisine: "Fast Food",
    rating: 4.0,
    time: "25 mins",
    minOrder: 99,
    image: "assets/images/swad.webp",
    menu: [
      { id: "m1", name: "VEG", price: 70, veg: true, image: "assets/images/Veg-Burger.jpg"},
      { id: "m2", name: "PANEER BURGER", price: 90, veg: true, image: "assets/images/paneer-burger.jfif"},
      { id: "m3", name: "VEG. GRILL SANDWICH", price: 80, veg: true, image: "assets/images/veg-grill-sandwich.jfif" },
      { id: "m4", name: "PANEER GRILL SANDWICH", price: 100, veg: true, image: "assets/images/Paneer-Sandwich.jpg" },
      { id: "m5", name: "PERI PERI FRIES", price: 120, veg: true, image: "assets/images/peri-peri-fries.jfif" },
      { id: "m6", name: "PLAIN MAGGIE", price: 60, veg: true, image: "assets/images/plain-maggi.jpeg" },
      { id: "m7", name: "PANEER MAGGIE", price: 80, veg: true, image: "assets/images/paneer-maggi.jpg" },
      { id: "m8", name: "VEG. CHOWMIN", price: 90, veg: true, image: "assets/images/veg-chowmin.jfif" },
      { id: "m9", name: "RED SAUSE PASTA", price: 130, veg: true, image: "assets/images/red-sauce-pasta.webp" },
      { id: "m10", name: "WHITE SAUSE PASTA", price: 160, veg: true, image: "assets/images/White-Sauce-Paste.jpg" },
      { id: "m11", name: "BHEL PURI", price: 60, veg: true, image: "assets/images/bhel-puri.jpg" },
      { id: "m12", name: "PANEER ROLL", price: 130, veg: true, image: "assets/images/PaneerRoll.jpg" },
      { id: "m13", name: "VEG. FRIED MOMO(8PCS)", price: 90, veg: true, image: "assets/images/fried-momo.webp" },
      { id: "m14", name: "VEG. STEAM MOMO(8PCS)", price: 110, veg: true, image: "assets/images/steam-momo.jpg" },
      { id: "m15", name: "MARGHERITA PIZZA", price: 150, veg: true, image: "assets/images/Pizza_Margherita.jpg" },
      { id: "m16", name: "PANEER PIZZA", price: 190, veg: true, image: "assets/images/Paneer-Pizza.jpg" },
      { id: "m17", name: "VEG OTC PIZZA", price: 170, veg: true, image: "assets/images/veg-pizza.webp" },
    ]
  },
  {
    id: "r3",
    name: "Prakash Cafe",
    cuisine: "Fast Food",
    rating: 4.2,
    time: "25 mins",
    minOrder: 99,
    image: "assets/images/prakash.webp",
    menu: [
      { id: "m1", name: "ALOO TIKKI BURGER", price: 90, veg: true, image: "assets/images/Veg-Burger.jpg"},
      { id: "m2", name: "SPECIAL BURGER", price: 110, veg: true, image: "assets/images/paneer-burger.jfif"},
      { id: "m3", name: "CHEESE SANDWICH", price: 70, veg: true, image: "assets/images/veg-grill-sandwich.jfif" },
      { id: "m4", name: "PANEER SANDWICH", price: 110, veg: true, image: "assets/images/Paneer-Sandwich.jpg" },
      { id: "m5", name: "FRENCH FRIES", price: 80, veg: true, image: "assets/images/peri-peri-fries.jfif" },
      { id: "m6", name: "MASALA MAGGIE", price: 70, veg: true, image: "assets/images/plain-maggi.jpeg" },
      { id: "m7", name: "CHEESE MAGGIE", price: 90, veg: true, image: "assets/images/cheese-maggi.jfif" },
      { id: "m8", name: "VEG. CHOWMIN", price: 110, veg: true, image: "assets/images/veg-chowmin.jfif" },
      { id: "m9", name: "RED PASTA", price: 100, veg: true, image: "assets/images/red-sauce-pasta.webp" },
      { id: "m10", name: "WHITE PASTA", price: 130, veg: true, image: "assets/images/White-Sauce-Paste.jpg" },
      { id: "m11", name: "VADA PAV", price: 60, veg: true, image: "assets/images/VADA-PAV.jfif" },
      { id: "m12", name: "SPRING ROLL", price: 110, veg: true, image: "assets/images/PaneerRoll.jpg" },
      { id: "m13", name: "CORN PIZZA", price: 220, veg: true, image: "assets/images/CORN-PIZZA.jpg" },
      { id: "m14", name: "FARM HOUSE PIZZA", price: 260, veg: true, image: "assets/images/FARM-HOUSE.avif" },
      { id: "m15", name: "PANEER TIKKA PIZZA", price: 230, veg: true, image: "assets/images/Paneer-Pizza.jpg" },
      { id: "m16", name: "PANEER PIZZA", price: 190, veg: true, image: "assets/images/Paneer-Pizza.jpg" },
      { id: "m17", name: "OTC PIZZA", price: 170, veg: true, image: "assets/images/veg-pizza.webp" },
    ]
  },
  {
    id: "r4",
    name: "Sonu Pastry & Ice Cream parlour",
    cuisine: "Fast Food & Cakes",
    rating: 4.2,
    time: "25 mins",
    minOrder: 99,
    image: "assets/images/sonu.webp",
    menu: [
  { id: "s1", name: "Black Forest Cake Slice", price: 85, veg: true, image: "assets/images/sonu-black-forest.jpg" },
  { id: "s2", name: "Butterscotch Pastry", price: 75, veg: true, image: "assets/images/sonu-butterscotch.jpg" },
  { id: "s3", name: "Pineapple Pastry", price: 70, veg: true, image: "assets/images/sonu-pineapple.jpg" },
  { id: "s4", name: "Red Velvet Pastry", price: 95, veg: true, image: "assets/images/sonu-red-velvet.jpg" },
  { id: "s5", name: "Chocolate Truffle Pastry", price: 90, veg: true, image: "assets/images/sonu-truffle.jpg" },
  { id: "s6", name: "Vanilla Ice Cream (1 Scoop)", price: 40, veg: true, image: "assets/images/sonu-vanilla-scoop.jpg" },
  { id: "s7", name: "MASALA PATIZ", price: 35, veg: true, image: "assets/images/masala-patties.jpg" },
  { id: "s8", name: "SAADA PATIZ", price: 25, veg: true, image: "assets/images/plain-patties.jpg" },
  { id: "s9", name: "BLACK FOREST CAKE (1/2 KG)", price: 350, veg: true, image: "assets/images/black-forest-cake.jpg" },
  { id: "s10", name: "BLACK FOREST CAKE (1 KG)", price: 550, veg: true, image: "assets/images/black-forest-cake-1kg.jpg" },
  { id: "s11", name: "COCA COLA", price: 40, veg: true, image: "assets/images/coca-cola.jpg" },
  { id: "s12", name: "THUMS UP", price: 40, veg: true, image: "assets/images/thums-up.jpg" },
  { id: "s13", name: "SPRITE", price: 40, veg: true, image: "assets/images/sprite.jpg" }
]

  },
  {
    id: "r5",
    name: "Chai Bar Cafe",
    cuisine: "Special Daal Baati",
    rating: 4.0,
    time: "25 mins",
    minOrder: 99,
    image: "assets/images/chai-bar.webp",
    menu: [
      { id: "m1", name: "Special Daal Baati(6pcs)", price: 70, veg: true, image: "assets/images/daal-baati.jpg"},
      { id: "m2", name: "MASALA PATIZ", price: 35, veg: true, image: "assets/images/masala-patties.jpg" }
    ]
  },
  {
    id: "r6",
    name: "Hotel veeras",
    cuisine: "Food",
    rating: 4.2,
    time: "25 mins",
    minOrder: 99,
    image: "assets/images/veeras.webp",
    menu: [
      { id: "v1", name: "Paneer Tikka", price: 220, veg: true, image: "assets/images/paneer-tikka.jpg" },
  { id: "v2", name: "Tandoori Soya Chaap", price: 200, veg: true, image: "assets/images/soya-chaap.jpg" },
  { id: "v3", name: "Hara Bhara Kebab", price: 180, veg: true, image: "assets/images/hara-bhara.jpg" },
  { id: "v4", name: "Chicken 65", price: 250, veg: false, image: "assets/images/chicken-65.jpg" },

  // 🍛 Main Course – Veg
  { id: "v5", name: "Dal Tadka", price: 150, veg: true, image: "assets/images/dal-tadka.jpg" },
  { id: "v6", name: "Paneer Butter Masala", price: 240, veg: true, image: "assets/images/paneer-butter-masala.jpg" },
  { id: "v7", name: "Mix Veg Masala", price: 180, veg: true, image: "assets/images/mix-veg.jpg" },
  { id: "v8", name: "Veg Biryani", price: 200, veg: true, image: "assets/images/veg-biryani.jpg" },

  // 🍛 Main Course – Non-Veg
  { id: "v9", name: "Chicken Curry", price: 260, veg: false, image: "assets/images/chicken-curry.jpg" },
  { id: "v10", name: "Mutton Curry", price: 340, veg: false, image: "assets/images/mutton-curry.jpg" },
  { id: "v11", name: "Egg Curry", price: 170, veg: false, image: "assets/images/egg-curry.jpg" },
  { id: "v12", name: "Chicken Biryani", price: 280, veg: false, image: "assets/images/chicken-biryani.jpg" },

  // 🍞 Breads & Rice
  { id: "v13", name: "Butter Naan", price: 40, veg: true, image: "assets/images/butter-naan.jpg" },
  { id: "v14", name: "Tandoori Roti", price: 30, veg: true, image: "assets/images/tandoori-roti.jpg" },
  { id: "v15", name: "Jeera Rice", price: 120, veg: true, image: "assets/images/jeera-rice.jpg" }

    ]
  },
  {
    id: "r7",
    name: "Vj Cafe & Restro",
    cuisine: "Fast Food",
    rating: 4.2,
    time: "25 mins",
    minOrder: 99,
    image: "assets/images/vj.webp",
    menu: [
      { id: "m1", name: "VEG. BURGER", price: 70, veg: true, image: "assets/images/Veg-Burger.jpg"},
      { id: "m2", name: "PANEER BURGER", price: 90, veg: true, image: "assets/images/paneer-burger.jfif"},
      { id: "m3", name: "VEG. GRILL SANDWICH", price: 80, veg: true, image: "assets/images/veg-grill-sandwich.jfif" },
      { id: "m4", name: "PANEER GRILL SANDWICH", price: 100, veg: true, image: "assets/images/Paneer-Sandwich.jpg" },
      { id: "m5", name: "PERI PERI FRIES", price: 120, veg: true, image: "assets/images/peri-peri-fries.jfif" },
      { id: "m6", name: "PLAIN MAGGIE", price: 60, veg: true, image: "assets/images/plain-maggi.jpeg" },
      { id: "m7", name: "PANEER MAGGIE", price: 80, veg: true, image: "assets/images/paneer-maggi.jpg" },
      { id: "m8", name: "VEG. CHOWMIN", price: 90, veg: true, image: "assets/images/veg-chowmin.jfif" },
      { id: "m9", name: "RED SAUSE PASTA", price: 130, veg: true, image: "assets/images/red-sauce-pasta.webp" },
      { id: "m10", name: "WHITE SAUSE PASTA", price: 160, veg: true, image: "assets/images/White-Sauce-Paste.jpg" },
      { id: "m11", name: "BHEL PURI", price: 60, veg: true, image: "assets/images/bhel-puri.jpg" },
      { id: "m12", name: "PANEER ROLL", price: 130, veg: true, image: "assets/images/PaneerRoll.jpg" },
      { id: "m13", name: "VEG. FRIED MOMO(8PCS)", price: 90, veg: true, image: "assets/images/fried-momo.webp" },
      { id: "m14", name: "VEG. STEAM MOMO(8PCS)", price: 110, veg: true, image: "assets/images/steam-momo.jpg" },
      { id: "m15", name: "MARGHERITA PIZZA", price: 150, veg: true, image: "assets/images/Pizza_Margherita.jpg" },
      { id: "m16", name: "PANEER PIZZA", price: 190, veg: true, image: "assets/images/Paneer-Pizza.jpg" },
      { id: "m17", name: "VEG OTC PIZZA", price: 170, veg: true, image: "assets/images/veg-pizza.webp" },
    ]
  },
  {
    id: "r8",
    name: "The Moon Light Cafe Niwai ",
    cuisine: "Fast Food",
    rating: 4.0,
    time: "25 mins",
    minOrder: 99,
    image: "assets/images/moonlight.webp",
    menu: [
      { id: "m1", name: "VEG. BURGER", price: 70, veg: true, image: "assets/images/Veg-Burger.jpg"},
      { id: "m2", name: "PANEER BURGER", price: 90, veg: true, image: "assets/images/paneer-burger.jfif"},
      { id: "m3", name: "VEG. GRILL SANDWICH", price: 80, veg: true, image: "assets/images/veg-grill-sandwich.jfif" },
      { id: "m4", name: "PANEER GRILL SANDWICH", price: 100, veg: true, image: "assets/images/Paneer-Sandwich.jpg" },
      { id: "m5", name: "PERI PERI FRIES", price: 120, veg: true, image: "assets/images/peri-peri-fries.jfif" },
      { id: "m6", name: "PLAIN MAGGIE", price: 60, veg: true, image: "assets/images/plain-maggi.jpeg" },
      { id: "m7", name: "PANEER MAGGIE", price: 80, veg: true, image: "assets/images/paneer-maggi.jpg" },
      { id: "m8", name: "VEG. CHOWMIN", price: 90, veg: true, image: "assets/images/veg-chowmin.jfif" },
      { id: "m9", name: "RED SAUSE PASTA", price: 130, veg: true, image: "assets/images/red-sauce-pasta.webp" },
      { id: "m10", name: "WHITE SAUSE PASTA", price: 160, veg: true, image: "assets/images/White-Sauce-Paste.jpg" },
      { id: "m11", name: "BHEL PURI", price: 60, veg: true, image: "assets/images/bhel-puri.jpg" },
      { id: "m12", name: "PANEER ROLL", price: 130, veg: true, image: "assets/images/PaneerRoll.jpg" },
      { id: "m13", name: "VEG. FRIED MOMO(8PCS)", price: 90, veg: true, image: "assets/images/fried-momo.webp" },
      { id: "m14", name: "VEG. STEAM MOMO(8PCS)", price: 110, veg: true, image: "assets/images/steam-momo.jpg" },
      { id: "m15", name: "MARGHERITA PIZZA", price: 150, veg: true, image: "assets/images/Pizza_Margherita.jpg" },
      { id: "m16", name: "PANEER PIZZA", price: 190, veg: true, image: "assets/images/Paneer-Pizza.jpg" },
      { id: "m17", name: "VEG OTC PIZZA", price: 170, veg: true, image: "assets/images/veg-pizza.webp" },
    ]
  },
];
